import type { Metadata } from "next";
import "./globals.css";
import Navbar from '@/components/navbar';

import { Poppins } from "next/font/google";

export const poppins = Poppins({subsets: ["latin"], weight: ["400"]});

export const metadata: Metadata = {
  title: "Bioforge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-black`} >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
